config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  get '/products/owner', to: "products#owner"
  #get '/products/best_offers', to: "products#best_offers"
  resources :products do
    resources :reviews, only: %i[create new show destroy index]
    collection do
      get :best_offers
    end
  end
  namespace :users do
    get '/products/cards', to: "products#cards"
    resources :products
  end

  resources :carts, only: %i[create show]
  resources :line_items, only: %i[create destroy show] do
    member do
      patch :increment
      patch :decrement
    end
  end
  resources :orders, only: %i[create destroy show edit index] do
    member do
      post :payment
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
   root "pages#home"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  name        :string
#  price       :float
#  stock       :integer
#  status      :boolean
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#  discount    :integer
#  category_id :bigint           not null
#
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, :description, :price, presence: true
  scope :ordered, -> { order(created_at: :desc) }
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_products_by_name_price_or_discount,
    against: [ :name, :price, :discount ],
    using: {
      tsearch: { prefix: true }
    }

    ORDER_BY = {
      "Newest" => "created_at DESC",
      "Best offers" => "discount DESC",
      "Best sellers" => "RANDOM()"
    }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    service = ProductService.new(params).call
    @products = service[:products].order(Product::ORDER_BY.fetch(params[:order_by], "created_at DESC"))
    @categories = service[:categories]
    @selected_category = service[:selected_category]
    @pagy, @products = pagy(@products, items: 20)
  end

  def show
    service = ProductService.new(params).show(params[:id], self)

    @product = service.product
    @review = service.review
    @reviews = service.reviews
    @average_rating = service.average_rating
    @pagy, @reviews = pagy(@product.reviews.order(created_at: :desc), items: 4)
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @products = Product.includes(:reviews).search_products_by_name_price_or_discount(params[:query])
    else
      @products = Product.includes(:reviews).ordered
    end
  end

  def cards
    if params[:query].present?
      @products = Product.includes(:reviews).search_products_by_name_price_or_discount(params[:query])
    else
      @products = Product.includes(:reviews).ordered
    end
  end

  def show
  end

  def edit
  end

  def create
    #@product = Product.new(product_params)
    #@product.user = current_user
    @product = current_user.products.build(product_params)
    if @product.save
      respond_to do |format|
       format.html { redirect_to users_products_url, notice: "Product was successfully created." }
       format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @product = Product.new
  end

  def destroy
    @product.destroy

    redirect_to users_products_url, notice: "Product was successfully destroyed.", status: :see_other
  end

  def update
    if @product.update(product_params)
      redirect_to users_products_path, notice: "Product was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :photo, :discount, :review, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users/products_helper.rb
module Users::ProductsHelper
end

app/views/users/products/_form.html.erb
<%= simple_form_for [:users, @product] do |f| %>

<div class="align-items-center p-4 gap-2 mb-3">
    <div class="flex-grow-1 fw-bold fs-5">
      <%= f.input :name, input_html: { class: 'form-control form-control-lg rounded-pill', placeholder: 'Add new product' } %>
    </div>
    <div class="flex-grow-1 fw-bold fs-5">
      <%= f.input :description, input_html: { class: 'form-control form-control-lg rounded-pill', placeholder: 'Add description' } %>
    </div>
    <div class="row g-2">
     <div class="col-md fw-bold fs-5">
      <%= f.input :price, input_html: { class: 'form-control form-control-lg rounded-pill', placeholder: 'Add price' } %>
      <%= f.input :discount, input_html: { class: 'form-control form-control-lg rounded-pill', placeholder: 'Add price' } %>
      </div>
      <div class="col-md fw-bold fs-5">
      <%= f.input :stock, input_html: { class: 'form-control form-control-lg rounded-pill', placeholder: '' } %>
    </div>
    <div class="col-md fw-bold fs-5">
      <%= f.input :photo, as: :file, input_html: { class: 'form-control form-control-lg rounded-pill', placeholder: '' } %>
    </div>
    <div class="col-md fw-bold fs-5">
      <%= f.association :category, prompt: "Choose a category", input_html: { class: 'form-control form-control-lg rounded-pill'} %>
    </div>
    </div>
      <%= f.submit @product.new_record? ? "Save" : "Update", class: 'btn btn-success p-2 mt-4 w-100' %>
      <%= link_to 'Back to Products', users_products_path,  class: "btn btn-dark mt-3" %>
    </div>
  </div>
<% end %>

app/views/users/products/_modal.html.erb
<div class="modal fade" id="productModal-<%= product.id %>">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="productModalLabel<%= product.id %>"><%=product.name%></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center">
        <h5 class="btn btn-dark btn-sm mt-3 position-absolute px-3 end-4 rounded-5 fw-bold"><%=rango = rand(10..40) %>% OFF</h5>
        <% if product.photo.attached? %>
          <%= image_tag url_for(product.photo), class: "card-img-top rounded-top", alt: product.name %>
        <% else %>
          <%= image_tag "no-image.jpg", class:"card-img-top rounded-top" %>
        <% end %>
         <h4 class="mt-3"><%= product.name %></h4>
              <p class="text-muted">stock: <%= product.stock %></p>
              <p><%= product.description %></p>
              <div class="d-flex justify-content-center ">
                <strong><h3 class="card-title mt-2 mb-2 fw-bold">$<%= number_with_precision(product.price, precision: 0) %></h3></strong>   <h6 class="discount mt-3 ms-1 me-3">$<%= number_with_precision(product.price * rango/100, precision: 0 )%></h6>
                <% average_rating = product.reviews.average(:rating)&.round(2) || 0 %>
                <%  average_rating.round.to_i.times do %>
                <i class="fa-solid fa-star mt-3" style="color: #FFD43B;"></i>
                <%end%>
          <h6 class="rating"><%= average_rating%></h6>
    </div>
      </div>
      <div class="modal-footer mt-4">
        <%= link_to "Edit", edit_users_product_path(product), class: "button btn btn-lg w-80 position-absolute bottom-0 start-0 end-0 mb-3 ms-3 me-3"%>
      </div>
      </div>
    </div>
  </div>

app/views/users/products/_product.html.erb
        <td ><%= image_tag product.photo.attached? ? product.photo : 'no-image.jpg', class:'avatar'  %></td>
          <td class="fw-bold "><%= product.name %></td>
          <td class="fw-bold"><%= product.price %></td>
          <td class="fw-bold"><%= product.stock %></td>
          <td class="fw-bold"> <%  product.discount.present? ? product.discount : '' %></td>
          <td <% average_rating = product.reviews.average(:rating)&.round(2) || 0 %>>
            <% average_rating.to_i.times do %>
              <i class="fa-solid fa-star mt-3" style="color: #FFD43B;"></i>
            <%end%>
          </td>
        <td>
          <div class="d-flex">
            <%= link_to "#", class: "btn btn-lg", data: { bs_toggle: "modal", bs_target: "#productModal-#{product.id}" } do %>
              <i class="fas fa-eye icono icono__blue" style="color: rgb(55, 106, 194);"></i>
            <% end %>
            <%= link_to edit_users_product_path(product), class:"btn btn-lg" do %>
                  <i class="fa-solid fa-pen-to-square" style="color:rgb(55, 106, 194);"></i>
            <% end %>
            <%= button_to users_product_path(product), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-lg" do %>
                  <i class="fa-solid fa-trash" style="color:rgb(228, 29, 29);"></i>
            <% end %>
          </div>
        </td>

    <%= render 'modal', product: product %>

app/views/users/products/_table.html.erb
<div class="table-responsive">
<table class="table table-hover me-5 mt-4 border shadow table-list">
    <thead class="table-list">
      <tr class="table-list">
        <th></th>
        <th>Product</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Discount</th>
        <th>Rating</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="table-list">
      <tr id="products"> </tr>
        <% products.each do |product| %>
          <% if controller_path == 'users/products' && product.user == current_user %>

           <tr id="<%= dom_id(product) %>">
              <%= render 'users/products/product', product: product %>
            </tr>

          <% end %>
        <%end%>
    </tbody>
  </table>
</div>

app/views/users/products/cards.html.erb
<div class="container p-3 mt-5">
  <div class="container my-4">
  <!-- Fila para buscador + botón -->
  <div class="row align-items-center">
    <!-- Buscador -->
    <div class="col-12 col-md-8 mb-2 mb-md-0">
      <%= form_with url: users_products_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control form-control-lg me-2",
            placeholder: "Search" %>
        <%= submit_tag "Search", class: "btn btn-outline-dark btn-lg" %>
      <% end %>
    </div>

    <!-- Botón de agregar -->
    <div class="col-12 col-md-4 text-md-end text-center mt-2 mt-md-0">
      <%= link_to "Add new product",
          new_users_product_path,
          data: { turbo_frame: :new_product },
          class: "btn btn-dark btn-lg px-4 fw-bold w-100 w-md-auto" %>
    </div>
  </div>

  <!-- Botones List / Cards -->
  <div class="row mt-4">
    <div class="col text-center">
      <div class="btn-group" role="group">
        <%= link_to "List", users_products_path, class: "btn btn-lg active buttongroup", id: "active" %>
        <%= link_to "Cards", users_products_cards_path, class: "btn btn-lg buttongroup" %>
      </div>
    </div>
  </div>
</div>
  <div class="row">
    <% @products.each do |product| %>
      <% if controller_path == 'users/products' && product.user == current_user %>
      <%= render "products/product", product: product %>
      <%end%>
    <%end%>
  </div>
</div>

app/views/users/products/create.turbo_stream.erb
<%= turbo_stream.append "products", partial: "users/products/product", locals: { product: @product} %>
<%= turbo_stream.remove "new_product" %>

app/views/users/products/destroy.html.erb
<h1>Users::Products#destroy</h1>
<p>Find me in app/views/users/products/destroy.html.erb</p>

app/views/users/products/edit.html.erb
<div class="container bg-white shadow mt-5 border rounded-4">
  <h1 class="my-4 mx-3">Edit Product</h1>

    <%= render 'form' %>
  
</div>

app/views/users/products/index.html.erb
<div class="container p-3 mt-5">
<div class="container my-4">
  <!-- Fila para buscador + botón -->
  <div class="row align-items-center">
    <!-- Buscador -->
    <div class="col-12 col-md-8 mb-2 mb-md-0">
      <%= form_with url: users_products_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control form-control-lg me-2",
            placeholder: "Search" %>
        <%= submit_tag "Search", class: "btn btn-outline-dark btn-lg" %>
      <% end %>
    </div>

    <!-- Botón de agregar -->
    <div class="col-12 col-md-4 text-md-end text-center mt-2 mt-md-0">
      <%= link_to "Add new product",
          new_users_product_path,
          data: { turbo_frame: :new_product },
          class: "btn btn-dark btn-lg px-4 fw-bold w-100 w-md-auto" %>
    </div>
  </div>

  <!-- Botones List / Cards -->
  <div class="row mt-4">
    <div class="col text-center">
      <div class="btn-group" role="group">
        <%= link_to "List", users_products_path, class: "btn btn-lg active buttongroup", id: "active" %>
        <%= link_to "Cards", users_products_cards_path, class: "btn btn-lg buttongroup" %>
      </div>
    </div>
  </div>
</div>

  <%= turbo_frame_tag :new_product %>

     <%= render partial: "users/products/table", locals: { products: current_user.products } %>
   <%#= render "products/product", product: product %>

</div>

app/views/users/products/new.html.erb
<div class="container bg-white shadow mt-5 border rounded-4">
  <h1 class="my-4 mx-3">Add New Product</h1>
  <%= turbo_frame_tag :new_product do %>
    <%= render 'form' %>
  <% end %>
</div>

<%# <turbo-frame id="new_product">
  </turbo-frame> %>

app/views/users/products/show.html.erb
<h1>Users::Products#show</h1>
<p>Find me in app/views/users/products/show.html.erb</p>