config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  get '/products/owner', to: "products#owner"
  #get '/products/best_offers', to: "products#best_offers"
  resources :products do
    resources :reviews, only: %i[create new show destroy index]
    collection do
      get :best_offers
    end
  end
  namespace :users do
    get '/products/cards', to: "products#cards"
    resources :products
  end

  resources :carts, only: %i[create show]
  resources :line_items, only: %i[create destroy show] do
    member do
      patch :increment
      patch :decrement
    end
  end
  resources :orders, only: %i[create destroy show edit index] do
    member do
      post :payment
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
   root "pages#home"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold" href="#">MyShop</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse bg-dark p-4  p-lg-0" id="navbarContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_url, class: "nav-link fw-bold fs-3 #{current_page?(root_url) ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_url, class: "nav-link fw-bold fs-3 #{current_page?(products_url) ? 'active' : ''}" %>
        </li>
      </ul>

      <% if controller_path == 'products' %>
        <div class="d-none d-lg-block mx-auto w-50" >
          <%= form_with url: products_path, method: :get, class: "d-flex", role: "search" do %>
            <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search" %>
            <%= submit_tag "Search", class: "btn btn-outline-light ms-2" %>
          <% end %>
        </div>
      <% end %>

      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag(
                  current_user.photo.attached? ? current_user.photo : '1077063.png',
                  class: "avatar dropdown-toggle",
                  id: "userDropdown",
                  data: { bs_toggle: "dropdown" },
                  'aria-haspopup': true,
                  'aria-expanded': false
                ) %>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><%= link_to "My products", users_products_path, class: "dropdown-item" %></li>
              <li><%= link_to "My orders", orders_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link fw-bold fs-4 text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary-custom ms-2 fs-4 text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
    <% if user_signed_in? %>
      <div class="d-flex align-items-center me-auto ms-2">
        <%= link_to cart_path(session[:cart_id]), class: "btn btn-outline-light btn-lg position-relative" do %>
          <i class="fa-solid fa-cart-shopping"></i>
          <%= render "carts/cart_count" %>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>


<% if controller_path == 'products' %>
  <div class="d-lg-none bg-dark p-2">
    <%= form_with url: products_path, method: :get, class: "d-flex", role: "search" do %>
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search" %>
      <%= submit_tag "Search", class: "btn btn-outline-light ms-2" %>
    <% end %>
  </div>
<% end %>