config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  get '/products/owner', to: "products#owner"
  #get '/products/best_offers', to: "products#best_offers"
  resources :products do
    resources :reviews, only: %i[create new show destroy index]
    collection do
      get :best_offers
    end
  end
  namespace :users do
    get '/products/cards', to: "products#cards"
    resources :products
  end

  resources :carts, only: %i[create show]
  resources :line_items, only: %i[create destroy show] do
    member do
      patch :increment
      patch :decrement
    end
  end
  resources :orders, only: %i[create destroy show edit index] do
    member do
      post :payment
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
   root "pages#home"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  name        :string
#  price       :float
#  stock       :integer
#  status      :boolean
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#  discount    :integer
#  category_id :bigint           not null
#
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, :description, :price, presence: true
  scope :ordered, -> { order(created_at: :desc) }
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_products_by_name_price_or_discount,
    against: [ :name, :price, :discount ],
    using: {
      tsearch: { prefix: true }
    }

    ORDER_BY = {
      "Newest" => "created_at DESC",
      "Best offers" => "discount DESC",
      "Best sellers" => "RANDOM()"
    }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    service = ProductService.new(params).call
    @products = service[:products].order(Product::ORDER_BY.fetch(params[:order_by], "created_at DESC"))
    @categories = service[:categories]
    @selected_category = service[:selected_category]
    @pagy, @products = pagy(@products, items: 20)
  end

  def show
    service = ProductService.new(params).show(params[:id], self)

    @product = service.product
    @review = service.review
    @reviews = service.reviews
    @average_rating = service.average_rating
    @pagy, @reviews = pagy(@product.reviews.order(created_at: :desc), items: 4)
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @products = Product.includes(:reviews).search_products_by_name_price_or_discount(params[:query])
    else
      @products = Product.includes(:reviews).ordered
    end
  end

  def cards
    if params[:query].present?
      @products = Product.includes(:reviews).search_products_by_name_price_or_discount(params[:query])
    else
      @products = Product.includes(:reviews).ordered
    end
  end

  def show
  end

  def edit
  end

  def create
    #@product = Product.new(product_params)
    #@product.user = current_user
    @product = current_user.products.build(product_params)
    if @product.save
      respond_to do |format|
       format.html { redirect_to users_products_url, notice: "Product was successfully created." }
       format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @product = Product.new
  end

  def destroy
    @product.destroy

    redirect_to users_products_url, notice: "Product was successfully destroyed.", status: :see_other
  end

  def update
    if @product.update(product_params)
      redirect_to users_products_path, notice: "Product was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :photo, :discount, :review, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users/products_helper.rb
module Users::ProductsHelper
end

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class:'text-black text-decoration-none catego', style:'' do %>
<li class='my-3'><%= category.name %></li>
<% end %>

app/views/products/_product.html.erb
<div class="grid-item position-relative bg-light card p-1 pt-2 mt-3 shadow" style="width: 18rem;">
  <div class="container">
    <% if controller_path == 'products' || controller_path == 'pages' %>
     <%= link_to "Details", product_path(product), class:"btn btn-dark btn-sm mt-3 me-2 position-absolute px-3 end-0 rounded-5 fw-bold" %>
    <% end %>
    <h5 class="btn btn-dark btn-sm mt-3 position-absolute px-3 end-4 rounded-5 fw-bold"><% if product.discount.present?  %><%= product.discount %>% OFF
        <%else %> 0% OFF
        <%end%></h5>
      <% if controller_path == 'users/products' && product.user == current_user %>
        <%= button_to "Remove", users_product_path(product), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm position-absolute top-0 end-0" %>
      <% end %>
<% if product.photo.attached? %>
    <%= image_tag product.photo, class:"card-img-top mt-2 mb-2 rounded-4" %>
  <%else%>
    <%= image_tag 'no-image.jpg', class:"card-img-top mb-3" %>
   <%end%>
  <div class="card-body">
    <div class= "d-flex justify-content-between">
    <h5 class="card-subtitle text-body-secondary ms-0"> <%= truncate(product.name, length: 20) %></h5>
    </div>
    <div class="d-flex ">
    <strong><h3 class="card-title mt-2 mb-2 fw-bold">$<%= number_with_precision(product.price, precision: 0) %></h3></strong>   <h6 class="discount mt-3 ms-1 me-3"><% if product.discount.present? %>$<%= number_with_precision(product.price * product.discount/100, precision: 0 )%>
    <%else%>
    <%end%></h6>
    <% average_rating = product.reviews.average(:rating)&.round(2) || 0 %>
    <%  average_rating.round.to_i.times do %>
    <i class="fa-solid fa-star mt-3" style="color: #FFD43B;"></i>
    <%end%>
    <h6 class="rating"><%= average_rating%></h6>
    </div>
    <% unless controller_path == 'users/products' && product.user == current_user %>
      <%= button_to line_items_path(product_id: product), method: :post, class: "button btn btn-lg w-80 position-absolute bottom-0 start-0 end-0 mb-3 ms-3 me-3" do %>
        <i class="fa-solid fa-cart-shopping"></i>
        <span class="">Add to cart</span>
      <%end%>
      <%else%>
      <%= link_to "Edit", edit_users_product_path(product), class: "button btn btn-lg w-80 position-absolute bottom-0 start-0 end-0 mb-3 ms-3 me-3"%>
    <%end%>


  </div>
</div>


</div>

app/views/products/_sidebar.html.erb
<div class="sidebar-bg ">

  <div class="accordion accordion-flush" id="categoriesAccordion">
    <div class="accordion-item border-0">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed fw-bold fs-5 text-white bg-transparent" type="button" data-bs-toggle="collapse" data-bs-target="#flush-categories" aria-expanded="false" aria-controls="flush-categories">
          Categories <i class="fa-solid fa-arrows-up-down ms-2"></i>
        </button>
      </h2>
      <div id="flush-categories" class="accordion-collapse collapse" data-bs-parent="#categoriesAccordion">
        <div class="accordion-body p-0">
          <ul class="list-unstyled">
            <%= render partial: 'category', collection: @categories %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-4">
    <h5 class="fw-bold text-white mb-3">Price Range</h5>
    <%= form_with url: products_path, method: :get, class: "price-filter-form" do |form| %>
      <div class="mb-3 mx-5">
        <%= form.number_field :min_price,
            class: "form-control rounded-pill",
            placeholder: "Min Price",
            onChange: 'this.form.requestSubmit()',
            value: params[:min_price] %>
      </div>
      <div class="mb-3 mx-5">
        <%= form.number_field :max_price,
            class: "form-control rounded-pill",
            placeholder: "Max Price",
            onChange: 'this.form.requestSubmit()',
            value: params[:max_price] %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<aside class="sidebar-bg ">
  <div class="d-grid gap-2 p-3">
    <div class="p-3 accordion button accordion-flush" id="accordionFlushExample">
      <div class="accordion-item ">
        <h2 class="accordion-header">
        <button class="accordion-button collapsed button text-white fw-bold fs-3" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          Categories <i class="fa-solid fa-arrows-up-down ms-3"></i>
        </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body fs-4 fw-bold">
            <ul class="list-unstyled">
              <%= render partial: 'category', collection: @categories %>
            </ul>
          </div>
        </div>
      </div>
  </div>

    <div class="grid text-center m-2">
      <h3 class="text-white fw-bold mt-1 mb-3 ">Price </h3>
      <%= form_with url: products_path, method: :get do |form| %>
        <div class="g-col-6"> <%= form.number_field :min_price,
                            class:" form-control form-control-lg rounded-pill mb-3",
                            placeholder: "min price",
                            onChange: 'this.form.requestSubmit()',
                            value: params[:min_price] %> </div>
        <div class="g-col-6"> <%= form.number_field :max_price,
                            class:" form-control form-control-lg rounded-pill",
                            placeholder: "max price",
                            onChange: 'this.form.requestSubmit()',
                            value: params[:max_price] %> </div>
      <% end %>



    </div>
  </div>
</aside>

<div class="container mt-5 ">
  <div class="d-flex flex-column flex-md-row justify-content-between align-items-center gap-3 mt-5">
    <h1>
      <% if @selected_category.present? %>
        <%= @selected_category.name %>
      <% elsif params[:order_by] == "Best offers" %>
        🔥 Best Offers
      <% elsif params[:order_by] == "Best sellers" %>
        🔥 Best Sellers
      <% else %>
        Products
      <% end %>
    </h1>

      <%= link_to products_path, class: 'btn btn-outline-dark fw-bold' do %>
        All products
      <% end %>
    <div>
      <%= form_with url: products_path, method: :get do |form| %>
        <%= form.select :order_by,
            options_for_select(Product::ORDER_BY.keys.map { |order| [order, order]}, params[:order_by]),
            {},
            class: "form-select form-select-lg my-5",
            onchange: 'this.form.requestSubmit()' %>
        <% end %>
    </div>
    <div class="pagy bg-light"><%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %></div>
  </div>

  <div class="row">
    <%= render @products %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container bg-white shadow mt-5 border rounded-4">
  <h1>Add New Product</h1>
 <%= render 'form' %>
</div>

app/views/products/owner.html.erb
<div class="container mt-5">
  <%= link_to 'Create a new product', new_product_path,  class: "btn btn-primary mt-4" if  params[:action] == 'owner' %>
  <div class="grid-container">
    <%= render @products %>
  </div>
 </div>

app/views/products/show.html.erb
<div class="container-fluid mt-4" id="container-show">
  <div class="row">
   
    <div class="col-lg-8 col-12 p-3">
      <div class="position-relative">
        <h5 class="btn btn-warning position-absolute px-3 end-0 top-0 mt-3 rounded-pill fw-bold shadow-sm discount1">
          <% if @product.discount.present?  %>
            <%= @product.discount %>% OFF
          <% else %>
            0% OFF
          <% end %>
        </h5>
        <% if @product.photo.attached? %>
          <%= image_tag @product.photo, class:"img-fluid rounded-4 shadow product-image" %>
        <% else %>
          <%= image_tag 'no-image.jpg', class:"img-fluid rounded-4 shadow product-image" %>
        <% end %>
      </div>

      <div class="container mt-4">
        <div class="d-flex flex-wrap justify-content-between align-items-center mb-3">
          <div class="d-flex align-items-center">
            <h1 class="me-3"><%= @product.name %></h1>
            <% @average_rating.round.to_i.times do %>
              <i class="fa-solid fa-star text-warning fs-4"></i>
            <% end %>
            <span class="ms-2 text-muted fs-5">(<%= @average_rating %>)</span>
          </div>
          <div class="text-end">
            <h2 class="text-dark">$<%= number_with_precision(@product.price, precision: 0) %></h2>
            <% if @product.discount.present? %>
              <h5 class="text-danger text-decoration-line-through">
                $<%= number_with_precision(@product.price * @product.discount / 100, precision: 0 ) %>
              </h5>
            <% end %>
          </div>
        </div>

        <p class="lead text-secondary mb-4"><%= @product.description %></p>

        <%= turbo_frame_tag "reviews" do %>
          <div class="d-flex align-items-center mb-2">
            <h2 class="me-2">Reviews</h2>
            <span class="text-muted">(<%= @reviews.count %> of <%= @product.reviews.count %>)</span>
          </div>

          <% if @reviews.present? %>
            <% @reviews.each do |review| %>
              <div class="border rounded-3 p-3 mb-3 shadow-sm bg-light">
                <div class="d-flex justify-content-between">
                  <div>
                    <p class="text-secondary small mb-1"><%= review.user.email %></p>
                    <h5><%= review.content %></h5>
                  </div>
                  <div class="text-end">
                    <% review.rating.times do %>
                      <i class="fa-solid fa-star text-warning"></i>
                    <% end %>
                    <% if current_user == review.user %>
                      <%= link_to product_review_path(@product, review),
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                        class: "btn btn-lg"  do %>
                        <i class="fa-solid fa-trash" style="color:rgb(228, 29, 29);"></i>
                        <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="pagy"><%== pagy_bootstrap_nav(@pagy) if @reviews.count >= 4 %></div>
          <% else %>
            <h4 class="text-muted mt-3">No reviews yet.</h4>
          <% end %>

          <%= button_to line_items_path(product_id: @product), method: :post, form: { data: { turbo: true } }, class: "btn btn-lg button mt-4 w-100" do %>
            <i class="fa-solid fa-cart-shopping me-2 "></i> Add to cart
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-lg-4 col-12 p-3">
      <div class="border p-4 rounded-4 shadow-sm bg-white">
        <h2 class="text-center mb-4">Add Review</h2>
        <%= simple_form_for [@product, @review] do |f| %>
          <div class="mb-3">
            <%= f.input :content, label: false, input_html: { class: 'form-control form-control-lg', placeholder: 'Write your thoughts' } %>
          </div>
          <div class="mb-3">
            <%= f.input :rating, collection: (1..5), label: "Rate this product", input_html: { data: { controller: "star-rating" }, class: 'form-control form-control-lg', id: 'stars' } %>
          </div>
          <%= f.submit "Submit Review", class: 'btn btn-primary w-100 py-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>