config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  get '/products/owner', to: "products#owner"
  #get '/products/best_offers', to: "products#best_offers"
  resources :products do
    resources :reviews, only: %i[create new show destroy index]
    collection do
      get :best_offers
    end
  end
  namespace :users do
    get '/products/cards', to: "products#cards"
    resources :products
  end

  resources :carts, only: %i[create show]
  resources :line_items, only: %i[create destroy show] do
    member do
      patch :increment
      patch :decrement
    end
  end
  resources :orders, only: %i[create destroy show edit index] do
    member do
      post :payment
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
   root "pages#home"
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :bigint           not null, primary key
#  product_id :bigint           not null
#  cart_id    :bigint
#  order_id   :bigint
#  quantity   :integer
#  price      :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  def total_price
    product.price * quantity
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]

  def show

  end

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)
    if @line_item.save

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to products_path, notice: 'Added to cart.' }
      end
    end
  end

  def new
  end

  def increment
    @cart = Cart.find session[:cart_id]
    @line_item = LineItem.find(params[:id])
    @line_item.increment!(:quantity)
    if @line_item.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to cart_path(@line_item.cart) }
      end
    end
  end

  def decrement
    @cart = Cart.find session[:cart_id]
    @line_item = LineItem.find(params[:id])
    if @line_item.quantity > 1
      @line_item.decrement!(:quantity)
    else
      @line_item.destroy
    end
    if @line_item.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to cart_path(@line_item.cart) }
      end
    end
  end

  def destroy
    @line_item = LineItem.find(params[:id])

      @line_item.destroy
      redirect_to cart_path(session[:cart_id]), notice: 'Product has been deleted.'

  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_item.html.erb
<div id="cart_item_<%= line_item.id %>", class="d-flex float-end align-items-center mt-4">
  <% if line_item.quantity > 1 %>
    <%= button_to decrement_line_item_path(line_item), method: :patch, class:"btn btn-danger" do %>
    <i class="fa-solid fa-minus"></i>
    <% end %>
  <% else %>
    <%= button_to 'Remove', line_item_path(line_item), method: :delete, class: 'btn btn-danger' %>
    <% end %>
  <span class="fs-5 border p-3 mx-3"> <%= line_item.quantity %> </span>
  <%= button_to increment_line_item_path(line_item), method: :patch, class:"btn btn-success" do %>
  <i class="fa-solid fa-plus"></i>
  <% end %>
</div>

app/views/line_items/cerate.html.erb
<h1>LineItems#cerate</h1>
<p>Find me in app/views/line_items/cerate.html.erb</p>

app/views/line_items/create.html.erb
<h1>LineItems#cerate</h1>
<p>Find me in app/views/line_items/cerate.html.erb</p>

app/views/line_items/create.turbo_stream.erb
<%= turbo_stream.replace "cart_count" do %>
  <%= render partial: "carts/cart_count", locals: { cart: @cart } %>
<% end %>

app/views/line_items/decrement.turbo_stream.erb
<%= turbo_stream.replace "cart_item_#{@line_item.id}" do %>
  <%= render partial: "line_items/item", locals: { line_item: @line_item } %>
<% end %>

<%= turbo_stream.replace "total", partial: 'carts/total',  locals: { cart: @cart } %>
<%= turbo_stream.replace "cart_count", partial:'carts/cart_count', locals: {cart: @cart} %>
<%= turbo_stream.replace "subtotal_#{@line_item.id}" do %>
  <%= render partial:'carts/subtotal', locals: {line_item: @line_item } %>
<% end %>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/line_items/increment.turbo_stream.erb
<%= turbo_stream.replace "cart_item_#{@line_item.id}" do %>
  <%= render partial: "line_items/item", locals: { line_item: @line_item } %>
<% end %>
<%#= turbo_stream.replace(@line_item) %>
<%= turbo_stream.replace "total", partial: 'carts/total',  locals: { cart: @cart } %>
<%= turbo_stream.replace "cart_count", partial:'carts/cart_count', locals: {cart: @cart} %>
<%= turbo_stream.replace "subtotal_#{@line_item.id}" do %>
  <%= render partial:'carts/subtotal', locals: {line_item: @line_item } %>
<% end %>

app/views/line_items/new.html.erb
<h1>LineItems#new</h1>
<p>Find me in app/views/line_items/new.html.erb</p>

app/views/line_items/show.html.erb
<h1>LineItems#show</h1>
<p>Find me in app/views/line_items/show.html.erb</p>